/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ObexAgentAdaptor -a obexagentadaptor obexagent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "obexagentadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ObexAgentAdaptor
 */

ObexAgentAdaptor::ObexAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ObexAgentAdaptor::~ObexAgentAdaptor()
{
    // destructor
}

QString ObexAgentAdaptor::Authorize(const QDBusObjectPath &transfer, const QString &bt_address, const QString &name, const QString &type, int length, int time)
{
    // handle method call org.openobex.Agent.Authorize
    QString path;
    QMetaObject::invokeMethod(parent(), "Authorize", Q_RETURN_ARG(QString, path), Q_ARG(QDBusObjectPath, transfer), Q_ARG(QString, bt_address), Q_ARG(QString, name), Q_ARG(QString, type), Q_ARG(int, length), Q_ARG(int, time));
    return path;
}

void ObexAgentAdaptor::Cancel()
{
    // handle method call org.openobex.Agent.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

